src/Entity/Key.php
<?php

namespace App\Entity;

use App\Repository\KeyRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=KeyRepository::class)
 * @ORM\Table(name="`key`")
 */
class Key
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $reference;

    /**
     * @ORM\Column(type="decimal", precision=5, scale=2,options={"default":0})
     */
    private $balance;

    /**
     * @ORM\Column(type="smallint",options={"default":0})
     */
    private $status;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $allocated_at;

    /**
     * @ORM\ManyToOne(targetEntity="Worker", inversedBy="keys")
     * @ORM\JoinColumn(name="worker_id", referencedColumnName="id")
     */
    private $worker;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getReference(): ?string
    {
        return $this->reference;
    }

    public function setReference(string $reference): self
    {
        $this->reference = $reference;

        return $this;
    }

    public function getBalance(): ?string
    {
        return $this->balance;
    }

    public function setBalance(string $balance): self
    {
        $this->balance = $balance;

        return $this;
    }

    public function getStatus(): ?int
    {
        return $this->status;
    }

    public function setStatus(int $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getAllocatedAt(): ?\DateTimeInterface
    {
        return $this->allocated_at;
    }

    public function setAllocatedAt(?\DateTimeInterface $allocated_at): self
    {
        $this->allocated_at = $allocated_at;

        return $this;
    }

    public function getWorker(): ?Worker
    {
        return $this->worker;
    }

    public function setWorker(?Worker $worker): self
    {
        $this->worker = $worker;

        return $this;
    }
}

src/Entity/Worker.php
<?php

namespace App\Entity;

use App\Repository\WorkerRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=WorkerRepository::class)
 */
class Worker
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $first_name;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $last_name;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $phone;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $department;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $function;

    /**
     * @ORM\Column(type="date")
     */
    private $take_on_at;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $dismiss_at;

    /**
     * @ORM\Column(type="date")
     */
    private $birthday;

    /**
     * @ORM\OneToMany(targetEntity="Key", mappedBy="worker")
     */
    private $keys;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getDepartment(): ?string
    {
        return $this->department;
    }

    public function setDepartment(string $department): self
    {
        $this->department = $department;

        return $this;
    }

    public function getFunction(): ?string
    {
        return $this->function;
    }

    public function setFunction(string $function): self
    {
        $this->function = $function;

        return $this;
    }

    public function getTakeOnAt(): ?\DateTimeInterface
    {
        return $this->take_on_at;
    }

    public function setTakeOnAt(\DateTimeInterface $take_on_at): self
    {
        $this->take_on_at = $take_on_at;

        return $this;
    }

    public function getDismissAt(): ?\DateTimeInterface
    {
        return $this->dismiss_at;
    }

    public function setDismissAt(?\DateTimeInterface $dismiss_at): self
    {
        $this->dismiss_at = $dismiss_at;

        return $this;
    }

    public function getBirthday(): ?\DateTimeInterface
    {
        return $this->birthday;
    }

    public function setBirthday(\DateTimeInterface $birthday): self
    {
        $this->birthday = $birthday;

        return $this;
    }

    public function __construct() {
        $this->keys = new ArrayCollection();
    }
}

src/Controller/KeyController.php
<?php
// src/Controller/KeyController.php
namespace App\Controller;


use App\Entity\Key;
use App\Entity\Worker;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/key")
 */
class KeyController extends AbstractController
{
    /**
     * @Route("/list",
     * name="key")
     */
    public function index()
    {
        $repository = $this->getDoctrine()->getRepository(Key::class);
        $notAllocatedKeys = $repository->workerNullOrNot('noWorker');

        $allocatedKeys = $this->getDoctrine()->getRepository(Key::class)->workerNullOrNot('worker');

        return $this->render('key/index.html.twig',[
            'notAllocatedKeys' => $notAllocatedKeys,
            'keys' => $allocatedKeys,
            "searchtext"=>null
        ]);
    }

    /**
     * @Route("/{id}/remove-allocation/{balance}",
     * name="removeallocation")
     */
    public function removeAllocation($id,$balance)
    {
        $key = $this->getDoctrine()->getRepository(Key::class)->find($id);
        $worker = $key->getWorker()->getId();
        if ($key && $worker){
            if ($balance != 0.00){
                return $this->render('key/remove-allocation.html.twig',[
                    'key' => $key,
                ]);
            }else{
                $key->setworker(null);
                $key->setBalance(0.00);
                $key->setAllocatedAt(null);
                $entityManager = $this->getDoctrine()->getManager('default');
                $entityManager->persist($key);
                $entityManager->flush();
                return $this->redirectToRoute('key');
            }
        }
        return $this->redirectToRoute('key');

    }
    /**
     * @Route("/{id}/add-allocation/{worker}",
     * name="addallocation",
     * defaults={ "worker"=0 })
     */
    public function addAllocation($id,$worker)
    {
        $key = $this->getDoctrine()->getRepository(Key::class)->findOneBy(['id'=>$id,'worker'=>null]);
        $workers = $this->getDoctrine()->getRepository(Worker::class)->findBy(['dismiss_at'=>null],["last_name" => "ASC","first_name"=>"ASC"]);
        if ($key){
            if ($worker == 0){
                return $this->render('key/add-allocation.html.twig',[
                    'key' => $key,
                    'workers' => $workers
                ]);
            }else{
                $newHolder = $this->getDoctrine()->getRepository(Worker::class)->find($worker);
                $key->setworker($newHolder);
                $key->setAllocatedAt(date_create(date("Y-m-d")));
                $entityManager = $this->getDoctrine()->getManager('default');
                $entityManager->persist($key);
                $entityManager->flush();
                return $this->redirectToRoute('key');
            }
        }
        return $this->redirectToRoute('key');

    }

    /**
     * @Route("/{id}/broken-key/{broken}",
     * name="brokenkey",
     * defaults={ "broken"=0 })
     */
    public function brokenKey($id,$broken)
    {
        $key = $this->getDoctrine()->getRepository(Key::class)->find($id);
        if ($key){
            if ($broken != 0){
                $key->setStatus(1);
                $entityManager = $this->getDoctrine()->getManager('default');
                $entityManager->persist($key);
                $entityManager->flush();
                return $this->redirectToRoute('key');
            }else{
                return $this->render('key/broken-key.html.twig',[
                    'key' => $key,
                ]);

            }
        }
        return $this->redirectToRoute('key');
    }

    /**
     * @Route("/{id}/add-balance/{add}",
     * name="addbalance",
     * defaults={ "add"=0 })
     */
    public function addBalance(Request $request,$id,$add)
    {
//        dd($request->request->get('balance'));
        $key = $this->getDoctrine()->getRepository(Key::class)->find($id);
        if ($key){
            if($add != 0){
                $key->setBalance($request->request->get('balance'));
                $entityManager = $this->getDoctrine()->getManager('default');
                $entityManager->persist($key);
                $entityManager->flush();
                return $this->redirectToRoute('key');
            }else{
                return $this->render('key/add-balance.html.twig',[
                    'key' => $key,
                ]);
            }

        }
        return $this->redirectToRoute('key');
    }

    /**
     * @Route("/keySearch",
     * name="keySearch")
     */
    public function keySearch(Request $request) {
  		$searchtext=$request->request->get('query');
  		$searchtext=str_replace("  "," ",$searchtext);
  		$searchlike="%".str_replace(" ","%",$searchtext)."%";
  		$entityManager = $this->getDoctrine()->getManager('default');
  		$queryBuilder = $entityManager->getRepository(Key::class)->createQueryBuilder('k');
  		$queryBuilder->where("k.status = 0");
      $queryBuilder->join('k.worker', 'w');
      $queryBuilder->Where("(
        k.reference LIKE :searchtext or
        w.first_name LIKE :searchtext or
        w.last_name LIKE :searchtext
        )");
  		$queryBuilder->orderBy('w.last_name', 'ASC');
      $queryBuilder->orderBy('w.first_name', 'ASC');
  		$queryBuilder->setParameter('searchtext',$searchlike);
  		$keys=$queryBuilder->getQuery()->getResult();
  		if ( !$keys ) {
  			$keys=[];
  		}
      // dd($keys);
  		return $this->render(
  			'key/index.html.twig',[
          'notAllocatedKeys' => null,
          "keys"=>$keys,
          "searchtext"=>$searchtext
        ]
  			);
  	}

}

templates/key/add-allocation.html.twig
{% extends '/base.html.twig' %}

{% block title %}Attribuer une clef{% endblock %}

{% block body %}
    <div class="col-md-12">
        <div class="box shadow-box">
            <div class="inbox">
                <h2 class="mb-4">Attribuer la clef : {{ key.reference }} </h2>
                <label for="worker">Quel salarié ?</label>
                <select id="worker" class="form-control mb-3">
                    <option value="0">Veuiller choisir un salarié</option>
                    {% for worker in workers %}
                        <option value="{{ worker.id }}">{{ worker.lastName |capitalize}} {{ worker.firstName |capitalize}}</option>
                    {% endfor %}
                </select>
                <div id="message" class="mb-5"></div>
                <a class="btn btn-sm btn-light" href="{{ path('key') }}">
                    <i class="fabut fas fa-arrow-left"></i>
                    Retour à la gestion des clefs
                </a>
                <a id="addAllocationBut" class="btn btn-sm btn-brown-reverse-outline float-right disabled" href="">
                    <i class="fabut fas fa-link"></i>
                    Attribuer
                </a>
            </div>
        </div>
    </div>

{% endblock %}

templates/key/add-balance.html.twig
{% extends '/base.html.twig' %}

{% block title %}Ajouter du solde{% endblock %}

{% block body %}
    <div class="col-md-12">
        <div class="box shadow-box">
            <div class="inbox">
                <h2 class="mb-4">Ajouter du solde à la clef :  <u>{{ key.reference }}</u> du porteur : <u>{{ key.worker.firstName | capitalize }} {{ key.worker.lastName | capitalize}}</u></h2>
                <form action="{{ path('addbalance', {id: key.id, add: 1}) }}" method="post" >
                    <div class="form-group">
                        <label for="new_balance">quel est le nouveau solde ?</label>
                        <div class="input-group mb-5" >
                            <input type="number" id="balance" name="balance"  class="form-control" min="{{ key.balance }}" max="10000.00" step="0.01" value="{{ key.balance }}">
                            <div class="input-group-append">
                                <span class="input-group-text">€</span>
                            </div>
                        </div>
                        <div id="message" class="mb-5"></div>
                        <a class="btn btn-sm btn-light" href="{{ path('key') }}">
                            <i class="fabut fas fa-arrow-left"></i>
                            Retour à la gestion des clefs
                        </a>
                        <button type="submit" id="addBalanceButton" class="btn btn-sm btn-brown-reverse-outline float-right disabled" >
                            <i class="fabut fas fa-euro-sign"></i>
                            Modifier le solde
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

templates/key/broken-key.html.twig
{% extends '/base.html.twig' %}

{% block title %}Signaler un problème{% endblock %}

{% block body %}
    <div class="col-md-12">
        <div class="box shadow-box">
            <div class="inbox">
                <h2 class="mb-4">signaler un problème sur la clef : {{ key.reference }}</h2>
                <label for="broken">Quel est le problème ?</label>
                <select id="broken" class="form-control mb-3">
                    <option value="0">Veuiller choisir un problème</option>
                    <option value="1">La clef est cassée</option>
                    <option value="2">La clef ne fonctionne plus</option>
                </select>
                <div id="message" class="mb-5"></div>
                <a class="btn btn-sm btn-light" href="{{ path('key') }}">
                    <i class="fabut fas fa-arrow-left"></i>
                    Retour à la gestion des clefs
                </a>
                <a  id="brokenBut" class="btn btn-sm btn-brown-reverse-outline float-right disabled" href="{{ path('brokenkey',{'id':key.id,"broken": 1}) }}" >
                    <i class="fabut fas fa-exclamation-circle"></i>
                    Signaler
                </a>
            </div>
        </div>
    </div>

{% endblock %}

templates/key/index.html.twig
{% extends '/base.html.twig' %}

{% block title %}Clefs{% endblock %}

{% block body %}
    <div class="col-md-12">
        <div class="box shadow-box">
            <div class="inbox">
                <div class="mb-4">
                    <h2 style="display: inline-block;" >Gestion des clefs</h2>
                    <form class="form-inline float-right" style="display: inline-block;"  action="{{ path('keySearch') }}" method="post">
                        <div class="input-group">
                            <input class="form-control" type="query" name="query" placeholder="Rechercher" aria-label="Search">
                            <button class="btn btn-brown-outline my-2 my-sm-0" type="submit"><i class="fas fa-search"></i></button>
                        </div>
                    </form>
                </div>
                {% if notAllocatedKeys %}
                    <h3 class="mb-4">Clefs libres</h3>
                    <table class="table table-hover">
                        <thead>
                        <tr>
                            <th>Réference</th>
                            <th style="width:15%">Actions</th>
                        </tr>
                        </thead>
                        <tboby>
                            {% for key in notAllocatedKeys %}
                            <tr>
                                <td>{{ key.reference }}</td>
                                <td>
                                    <div class="btn-group" role="group">
                                        <button id="btnGroupDrop1" type="button" class="btn btn-sm btn-brown-outline dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            Actions
                                        </button>
                                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="btnGroupDrop1">
                                            <a class="dropdown-item" href="{{ path('addallocation',{'id':key.id,"worker":0}) }}">
                                                <i class="fabut fas fa-link"></i>
                                                Attribuer la clefs
                                            </a>
                                            <a class="dropdown-item" href="{{ path('brokenkey',{'id':key.id,"broken":0}) }}">
                                                <i class="fabut fas fa-exclamation-circle"></i>
                                                Signaler un problème
                                            </a>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            {% endfor %}
                        </tboby>
                    </table>

                    <hr>
                    <h3 class="mb-4">Clefs Attribuées</h3>
                {% else %}
                    {% if searchtext %}
                        <h3 class="mb-4" >Resultat de la recherche : {{ searchtext }}</h3>
                    {% else %}
                        <h3 class="mb-4">Liste des clefs</h3>
                    {% endif %}
                {% endif %}
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th style="width:30%">Réference</th>
                        <th style="width:15%">Nom</th>
                        <th style="width:15%">Prénom</th>
                        <th style="width:10%">Solde</th>
                        <th style="width:15%">Attribuer le</th>
                        <th style="width:15%">Actions</th>
                    </tr>
                    </thead>
                    <tboby>
                        {% for key in keys %}
                            <tr>
                                <td>{{ key.reference }}</td>
                                <td>{{ key.worker.lastName |capitalize }}</td>
                                <td>{{ key.worker.firstName |capitalize }}</td>
                                <td class="text-right">{{ key.balance |number_format(2) }} €</td>
                                <td>{{ key.allocatedAt |date("d-m-Y") }}</td>
                                <td>
                                    <div class="btn-group" role="group">
                                        <button id="btnGroupDrop1" type="button" class="btn btn-sm btn-brown-outline dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            Actions
                                        </button>
                                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="btnGroupDrop1">
                                            <a class="dropdown-item" href="{{ path('addbalance',{'id':key.id}) }}">
                                                <i class="fabut fas fa-euro-sign"></i>
                                                Ajouter du solde
                                            </a>
                                            <a class="dropdown-item" href="{{ path('removeallocation',{'id':key.id,"balance":key.balance |number_format(2, '.', ' ')}) }}">
                                                <i class="fabut fas fa-unlink"></i>
                                                Retirer la clefs
                                            </a>
                                            <a class="dropdown-item" href="{{ path('brokenkey',{'id':key.id,"broken":0}) }}">
                                                <i class="fabut fas fa-exclamation-circle"></i>
                                                Signaler un problème
                                            </a>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        {% endfor %}
                    </tboby>
                </table>
                {% if keys == null %}
                    <p class="text-center font-weight-bold">
                        Aucunes clefs trouvées
                    </p>
                {% endif %}
            </div>
        </div>
    </div>

{% endblock %}

templates/key/remove-allocation.html.twig
{% extends '/base.html.twig' %}

{% block title %}Retirer la clefs{% endblock %}

{% block body %}
    <div class="col-md-12">
        <div class="box shadow-box">
            <div class="inbox">
                <h2 class="mb-4">Retirer la clef : <u>{{ key.reference }}</u> du porteur : <u>{{ key.worker.firstName | capitalize }} {{ key.worker.lastName | capitalize}}</u></h2>
                <p class="mb-4 text-danger text-center">
                    <i class="fas fa-exclamation-triangle mr-3"></i>
                    Le solde de la clef sera remis à <strong>0.00 €</strong>
                    <i class="fas fa-exclamation-triangle ml-3"></i>
                    <br>
                    Il est actuellement de <strong>{{ key.balance |number_format(2, '.', ' ') }} € </strong>
                </p>
                <a class="btn btn-sm btn-light" href="{{ path('key') }}">
                    <i class="fabut fas fa-arrow-left"></i>
                    Retour à la gestion des clefs
                </a>
                <a class="btn btn-sm btn-brown-reverse-outline float-right" href="{{ path('removeallocation',{'id':key.id,"balance": 0.00}) }}">
                    <i class="fabut fas fa-unlink"></i>
                    Valider le retrait
                </a>
            </div>
        </div>
    </div>

{% endblock %}