src/Entity/Device.php
<?php

namespace App\Entity;

use App\Repository\DeviceRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=DeviceRepository::class)
 */
class Device
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $reference;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $type;

    /**
     * @ORM\Column(type="date")
     */
    private $last_restock;

    /**
     * @ORM\Column(type="date")
     */
    private $next_restock;

    /**
     * @ORM\Column(type="date")
     */
    private $last_maintenance;

    /**
     * @ORM\Column(type="date")
     */
    private $next_maintenance;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getReference(): ?string
    {
        return $this->reference;
    }

    public function setReference(string $reference): self
    {
        $this->reference = $reference;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getLastRestock(): ?\DateTimeInterface
    {
        return $this->last_restock;
    }

    public function setLastRestock(\DateTimeInterface $last_restock): self
    {
        $this->last_restock = $last_restock;

        return $this;
    }

    public function getNextRestock(): ?\DateTimeInterface
    {
        return $this->next_restock;
    }

    public function setNextRestock(\DateTimeInterface $next_restock): self
    {
        $this->next_restock = $next_restock;

        return $this;
    }

    public function getLastMaintenance(): ?\DateTimeInterface
    {
        return $this->last_maintenance;
    }

    public function setLastMaintenance(\DateTimeInterface $last_maintenance): self
    {
        $this->last_maintenance = $last_maintenance;

        return $this;
    }

    public function getNextMaintenance(): ?\DateTimeInterface
    {
        return $this->next_maintenance;
    }

    public function setNextMaintenance(\DateTimeInterface $next_maintenance): self
    {
        $this->next_maintenance = $next_maintenance;

        return $this;
    }
}

src/Controller/DashboardController.php
<?php
// src/Controller/DashboardController.php
namespace App\Controller;


use App\Entity\Device;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;


/**
 * @Route("/dashboard")
 */
class DashboardController extends AbstractController
{

    public function index()
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        $devices = $this->getDoctrine()->getRepository(Device::class)->findAllOrderedBy('reference');
        $maintenances = $this->getDoctrine()->getRepository(Device::class)->findAllOrderedBy('next_maintenance');
        $restocks = $this->getDoctrine()->getRepository(Device::class)->findAllOrderedBy('next_restock');

        return $this->render('dashboard/index.html.twig',[
            'devices' => $devices,
            'maintenances' => $maintenances,
            'restocks' => $restocks
        ]);
    }

    /**
     * @Route("/{id}/restock/{date}",
     * name="restock",
     * defaults={ "date"=0 })
     */
    public function restock($id,$date)
    {
        $device = $this->getDoctrine()->getRepository(Device::class)->find($id);
        if ($device){
            if ($date != 0){
                $oldDate = date_create($date);
                $newDate = date_add($oldDate, date_interval_create_from_date_string('1 days'));
            }else{
                $nextDate = date_create($device->getNextRestock()->format("Y-m-d"));
                $newDate = date_add($nextDate, date_interval_create_from_date_string('-3 days'));
            }
            return $this->render('dashboard/restock.html.twig',[
                'device' => $device,
                'date' => $newDate
            ]);
        }

        return $this->redirectToRoute('dashboard');

    }

    /**
     * @Route("/{id}/new-date-restock/{date}",
     * name="saverestock")
     */
    public function saveRestock($id,$date)
    {
        $device = $this->getDoctrine()->getRepository(Device::class)->find($id);
        if ($device){
            $device->setNextRestock(date_create($date));
            $entityManager = $this->getDoctrine()->getManager('default');
            $entityManager->persist($device);
            $entityManager->flush();
            return $this->redirectToRoute('dashboard');
        }
        return $this->redirectToRoute('dashboard');
    }


    /**
     * @Route("/{id}/maintenance/{date}",
     * name="maintenance",
     * defaults={ "date"=0 })
     */
    public function maintenance($id,$date)
    {
        $device = $this->getDoctrine()->getRepository(Device::class)->find($id);
        if ($device){
            if ($date != 0){
                $oldDate = date_create($date);
                $newDate = date_add($oldDate, date_interval_create_from_date_string('1 days'));
            }else{
                $today = date_create(date("y-m-d"));
                $newDate = date_add($today, date_interval_create_from_date_string('2 days'));
            }
            return $this->render('dashboard/maintenance.html.twig',[
                'device' => $device,
                'date' => $newDate
            ]);
        }

        return $this->redirectToRoute('dashboard');

    }

    /**
     * @Route("/{id}/new-date-maintenance/{date}",
     * name="savemaintenance")
     */
    public function saveMaintenance($id,$date)
    {
        $device = $this->getDoctrine()->getRepository(Device::class)->find($id);
        if ($device){
            $device->setNextMaintenance(date_create($date));
            $entityManager = $this->getDoctrine()->getManager('default');
            $entityManager->persist($device);
            $entityManager->flush();
            return $this->redirectToRoute('dashboard');
        }
        return $this->redirectToRoute('dashboard');
    }


}

templates/dashboard/index.html.twig
{% extends '/base.html.twig' %}

{% block title %}Dashboard{% endblock %}

{% block body %}
    <div class="col-md-8">
        <div class="box shadow-box">
            <div class="inbox">
                <h2>Dashboard</h2>
                <h3>Mes distributeurs</h3>
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th>Machine</th>
                        <th>Type</th>
                        <th>Réassort</th>
                        <th>Maintenance</th>
                        <th style="width:15%">Actions</th>
                    </tr>
                    </thead>
                    <tboby>
                        {% for device in devices %}
                            <tr>
                                <td>{{ device.reference }}</td>
                                <td>{{ device.type }}</td>
                                <td>{{ device.lastRestock |date("d-m-Y") }}</td>
                                <td>{{ device.lastMaintenance |date("d-m-Y") }}</td>
                                <td>
                                    <div class="btn-group" role="group">
                                        <button id="btnGroupDrop1" type="button" class="btn btn-sm btn-brown-outline dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            Actions
                                        </button>
                                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="btnGroupDrop1">
                                            <a class="dropdown-item" href="{{ path('restock',{'id':device.id,'date':0}) }}">
                                                <i class="fabut fas fa-dolly"></i>
                                                Demande de réassort
                                            </a>
                                            <a class="dropdown-item" href="{{ path('maintenance',{'id':device.id}) }}">
                                                <i class="fabut fas fa-tools"></i>
                                                Signaler une panne
                                            </a>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        {% endfor %}
                    </tboby>
                </table>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="box shadow-box scroll">
            <div class="inbox">
                <h2>Actions Cofee Time</h2>
                <h3>Prochains réassort</h3>
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>Machine</th>
                            <th>Date</th>
                        </tr>
                    </thead>
                    <tboby>
                        {% for restock in restocks %}
                            <tr>
                                <td>{{ restock.reference }}</td>
                                <td>{{ restock.nextRestock |date("d-m-Y") }}</td>
                            </tr>
                        {% endfor %}
                    </tboby>
                </table>
                <hr>
                <h3>Prochaines maintenance</h3>
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th>Machine</th>
                        <th>Date</th>
                    </tr>
                    </thead>
                    <tboby>
                        {% for maintenance in maintenances %}
                            <tr>
                                <td>{{ maintenance.reference }}</td>
                                <td>{{ maintenance.nextMaintenance |date("d-m-Y") }}</td>
                            </tr>
                        {% endfor %}
                    </tboby>
                </table>
            </div>
        </div>
    </div>

{% endblock %}

templates/dashboard/maintenance.html.twig
{% extends '/base.html.twig' %}

{% block title %}Demande de maintenance{% endblock %}

{% block body %}
    <div class="col-md-12">
        <div class="box shadow-box">
            <div class="inbox">
                <h2 class="mb-4">Demande de maintenance pour le distributeur : {{ device.reference }} - {{ device.type }}</h2>
                <p class="mb-5">
                    Nous pouvons vous proposer une intervention le <strong> {{ date|date("d-m-Y") }} </strong>
                </p>
                <a class="btn btn-sm btn-light" href="{{ path('dashboard') }}">
                    <i class="fabut fas fa-arrow-left"></i>
                    Retour au dashboard
                </a>
                <a class="btn btn-sm btn-brown-reverse-outline float-right" href="{{ path('savemaintenance',{'id':device.id,"date": date|date("d-m-Y") }) }}">
                    <i class="fabut far fa-calendar-check"></i>
                    Valider la nouvelle date
                </a>
                <a class="btn btn-sm btn-brown-outline float-right mr-1" href="{{ path('maintenance',{'id':device.id, "date": date |date("d-m-Y")}) }}">
                    <i class="fabut far fa-calendar-times"></i>
                    Demander une autre date
                </a>

            </div>
        </div>
    </div>

{% endblock %}

templates/dashboard/restock.html.twig
{% extends '/base.html.twig' %}

{% block title %}Demande de réassort{% endblock %}

{% block body %}
    <div class="col-md-12">
        <div class="box shadow-box">
            <div class="inbox">
                <h2 class="mb-4">Demande de réassort pour le distributeur : {{ device.reference }} - {{ device.type }}</h2>
                <p class="mb-4">
                    Le prochain réassort est prévue le {{ device.nextRestock |date("d-m-Y") }}
                </p>
                <p class="mb-5">
                    Nous pouvons vous proposer une intervention le <strong> {{ date |date("d-m-Y") }} </strong>
                </p>
                <a class="btn btn-sm btn-light" href="{{ path('dashboard') }}">
                    <i class="fabut fas fa-arrow-left"></i>
                    Retour au dashboard
                </a>
                <a class="btn btn-sm btn-brown-reverse-outline float-right" href="{{ path('saverestock',{'id':device.id,"date":date |date("Y-m-d") }) }}">
                    <i class="fabut far fa-calendar-check"></i>
                    Valider la nouvelle date
                </a>
                <a class="btn btn-sm btn-brown-outline float-right mr-1" href="{{ path('restock',{'id':device.id, "date": date |date("d-m-Y")}) }}">
                    <i class="fabut far fa-calendar-times"></i>
                    Demander une autre date
                </a>
            </div>
        </div>
    </div>

{% endblock %}